: linux
language: rust
cache: cargo
before_cache:
rust: stable
branches:
  only:
    # This is where pull requests from "bors r+" are built.
    - staging
    # This is where pull requests from "bors try" are built.
    - trying
    # Always build master & Enable building pull requests.
    - master
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
  include:
    - {}
    - rust: beta
    - rust: nightly
      cache: false
      script:
        - cargo test --no-default-features --features "std cargo" -p axon:0.1.0
        - cargo test --features "yaml unstable doc"
    - name: Linting (fmt + clippy)
      before_script:
        - rustup component add clippy
        - rustup component add rustfmt
      script:
        - echo "Checking codebase with Clippy release `cargo clippy --version`."
        - cargo clippy --lib --features "yaml unstable" -- -D warnings
        - cargo clippy --tests --examples --features "yaml unstable" -- -D warnings
        - cargo fmt -- --check
    - name: Coverage
      addons:
        apt:
          packages:
            - libssl-dev
            - cmake
            - pkg-config
            - zlib1g-dev
          update: true
      before_script:
        - cargo install cargo-tarpaulin
      script:
        - cargo tarpaulin --workspace --features "yaml unstable" --ciserver travis-ci --coveralls $TRAVIS_JOB_ID --timeout 300
script:
  - cargo test --no-default-features --features "std cargo" -p axon:0.1.0
  - cargo test --features "yaml unstable"
notifications:
  email: false
